hmrc/plastic-packaging-tax-registration-frontend

- app/uk/gov/hmrc/plasticpackagingtax/registration/connectors/GenericRegistrationConnector.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/HonestyDeclarationController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/honesty_declaration.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/registration_page.scala.html
- build.sbt
- conf/app.routes
- conf/messages.en
- test/spec/ControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/HonestyDeclarationControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/RegistrationControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/HonestyDeclarationViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/RegistrationViewSpec.scala
**Create the Honesty Declaration page**
* This is a page that will allow us to integrate with the Generic registration service.
* In order to connect to the Generic Registration service we require a `/POST` request to be made between our service and the generic registration service.
* This means we need to control that interaction via a `/POST` request to our own service, as we should avoid `/GET` requests.
**Integrate 'honesty-declaration' with 'registration' page**
* Took the liberty to create indentation on the
`registration_page.scala.html` page to help read the code a bit better.
* The other links on the registration page should probably point to the
current registration page for the time being, instead of pointing to a
non-existing page.
> PPTP-291 Create Declaration page

- README.md
- app/uk/gov/hmrc/plasticpackagingtax/registration/config/AppConfig.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/connectors/IncorpIdConnector.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/HonestyDeclarationController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/IncorpIdController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/genericregistration/IncorpIdCreateRequest.scala
- conf/app.routes
- conf/application.conf
- project/AppDependencies.scala
- test/base/it/ConnectorISpec.scala
- test/base/it/WiremockTestServer.scala
- test/base/unit/ControllerSpec.scala
- test/base/unit/UnitViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/config/AppConfigSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/config/ErrorHandlerTest.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/connectors/IncorpIdConnectorISpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/HonestyDeclarationControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/IncorpIdControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/RegistrationControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/FooterViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/HonestyDeclarationViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/RegistrationViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/StartViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/model/TitleSpec.scala
This is just the integration between PPT FE and the IncorpID FE
microservice.
I have also organised the base spec folder, separating the `unit` and `integration` base setup.
```
Outstanding work is to save the `journeyId` from the IncorpId FE
microservice in order to manage the statuses of each task.
Subsequent tickets will address the above.
```
> PPTP-292 Incorporated Entity Identification FE integration

- app/uk/gov/hmrc/plasticpackagingtax/registration/config/AppConfig.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/partials/phaseBanner.scala.html
- conf/application.conf
- test/uk/gov/hmrc/plasticpackagingtax/registration/config/AppConfigSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/partials/PhaseBannerSpec.scala
I mistakingly inserted the `contact-frontend` service on our lists of
microservice dependencies, when we do not need that, as we simply
require a HMRC base URI, as we did with the exit survey.
In order to provide the `backUrl` logic on the `contact-frontend`
service we will need to use the `platform.frontend.host` property which
is available on all environments, but we need to have a fallback
solution for local.
> PPTP-389 Change the feedback link construction

- app/assets/stylesheets/_cards.scss
- app/assets/stylesheets/application.scss
Because we are sort of sharing the same URI between PPT registrations FE
and PPT returns FE, it could be that there is a confusion on what CSS to
load and probably PPT registrations FE is overriding the CSS config.
It works well locally because the domain (IP:PORT) is different and
there is no "confusion" there.
In QA the domain and start of URI is the same.
> BAU - Attempt to load missing CSS on PPT Returns FE

- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewRegistrationController.scala
- test/base/unit/ControllerSpec.scala
- test/spec/PptTestData.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewRegistrationControllerSpec.scala
I have made a mistake and added the userHeaders to the incorrect
registration instance/version and the tests did not capture it.
So this is about adding the headers to the correct registrations
instance and updating the unit tests.
> PPTP-757 Add user headers to correct Registration payload

- tampermonkey/PPT_Auth_AutoComplete.js
@tmc-ee mentioned that on the returns journey he was seeing two `QuickSubmit` buttons, this is due to the returns and registration microservice sharing the same base URI.
One quick and easy way is to override the buttons on top of each other.
As this is just to help stakeholders navigate on the test environments is should not be an issue.
> PPTP-925 'QuickButton' style position is 'absolute'

- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/actions/AuthAction.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/actions/EmailAllowedList.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/request/AuthenticatedRequest.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/request/JourneyAction.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/request/JourneyRequest.scala
- conf/application.conf
- tampermonkey/PPT_Auth_AutoComplete.js
- test/base/MockAuthAction.scala
- test/base/PptTestData.scala
- test/base/unit/ControllerSpec.scala
- test/base/unit/UnitViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/actions/AuthActionSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/actions/EmailAllowedListProviderSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/actions/EmailAllowedListSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/models/request/JourneyActionSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/partials/PhaseBannerSpec.scala
* At the beginning of Alpha phase we have used UTR to save the registration user journey progress.
As we progressed through Alpha, we were told that two legal entities we had to support woud not have an UTR. 
* This work is about replacing the enrolment key UTR with the User Internal Id, which is always present in the Auth record and is unique to this user.
* This will allow us to continue to support the "Save And Come Back Later" functionality.
* Prior to this ticket we also had a UTR allowlist which will have to be replaced with an email allowlist, which is a standard practice in other HMRC services during Private Beta phase.
* Once in Private Beta we will be required to filter early bird users on our service, one way would to filter by their email addresses. This is a common practice …
> PPTP-893 Use 'InternalId' to save registration progress 

- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewRegistrationController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/MetaData.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewRegistrationControllerSpec.scala
These are only required to be capture on the FE and when CiP auditing the
registration.
> PPTP-994 Make Metadata NrsDetails optional

- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/LiabilityStartDateController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/LiabilityWeightController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/check_liability_details_answers_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/liability_start_date_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/liability_weight_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/start_page.scala.html
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/LiabilityStartDateControllerTest.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/LiabilityWeightControllerTest.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/CheckLiabilityDetailsAnswersViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/LiabilityStartDateViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/LiabilityWeightViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/StartViewSpec.scala
Work includes:
* Link Start page to Plastic Weight page
* Make 'Liability Weight' the first PPT 
* Make 'Liability Start Date' the 2nd PPT page
* Change Liability Details CYAP 'Back' link 
UAT changes can be found [here](https://github.com/hmrc/plastic-packaging-tax-acceptance/pull/44)
> PPTP-1026  - Liability Check - Move Liability section

- app/uk/gov/hmrc/plasticpackagingtax/registration/views/check_liability_details_answers_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/registration_page.scala.html
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/CheckLiabilityDetailsAnswersViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/LiabilityWeightViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/PartnershipTypeViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/RegistrationViewSpec.scala
* **PPTP-2019 Change Liability link on TaskList page**
The /GET link should be the Liability Weight questions and no longer the
Liability Start date question, as based on UR we have swapped them.
* **PPTP-2019 Re-order answers on Liability CYAP**
* **BAU - Clean imports**
> PPTP-2019 Change Liability Task List link and Re-order CYAP answers

- app/uk/gov/hmrc/plasticpackagingtax/registration/views/liability_weight_page.scala.html
- conf/messages.en
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/LiabilityWeightViewSpec.scala
Refactored to be consistent with the latest version in the prototype. In order to include all the necessary help text and remain compliant with the GDS guidelines, I had to remove use of the main page question as a text field heading and add the main question and help text as separate page pieces.
> PPTP-1017 : Capture PPT weight page refactor

- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/NotLiableController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/components/link.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/components/pageHeading.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/components/paragraph.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/components/subHeading.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/liability_weight_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/not_liable.scala.html
- conf/app.routes
- conf/messages.en
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/NotLiableControllerTest.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/NotLiableViewSpec.scala
I've added some new Twirl components for common page elements which encapsulate use of the required govuk css classes and back-ported their use to the liability weight page. I've used HTML ids more judiciously on the not liable page which (I believe) makes the unit tests less brittle.
> PPTP-1018 : New not liable page

- app/uk/gov/hmrc/plasticpackagingtax/registration/config/AppConfig.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/CheckLiabilityDetailsAnswersController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/LiabilityLiableDateController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/LiabilityWeightController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/NotLiableController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/forms/LiabilityLiableDate.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/LiabilityDetails.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/check_liability_details_answers_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/liability_liable_date_page.scala.html
- conf/app.routes
- conf/application.conf
- conf/messages.en
- tampermonkey/PPT_AutoComplete.js
- test/base/unit/UnitViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/config/AppConfigSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/CheckLiabilityDetailsAnswersControllerTest.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/LiabilityLiableDateControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/LiabilityWeightControllerTest.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/NotLiableControllerTest.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/LiabilityDetailsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/CheckLiabilityDetailsAnswersViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/LiabilityLiableDateViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/LiabilityStartDateViewSpec.scala
* **Create 'liabilityPreLaunch' feature flag**
This will help us swap between two pages in the liability section.
Before the 6th April 2022 it shoud be enabled, and disabled after that.
* **Add Liable Date page to Liability details section'**
* **PPTP-1020 Update liability pre-launch URI**
This will very likely be changed in the future by our product team to
reflect the action on the page.
* **Wiring 'NotLiable' page into the Liability journey**
Remove unnecessary class parameters from the `NotLiableController`
* **Rename 'isLiabilityPreLaunchEnabled' with 'isPreLaunch'**
> PPTP-1020 Liability Check - 3. Will you still be liable in April 22 Page?

- .github/pull_request_template.md
* Render checkboxes correctly on GitHub - The unchecked checkboxes need to have a space between the rectangular
braces.
> PPTP-1054 Test PR Template

- app/uk/gov/hmrc/plasticpackagingtax/registration/views/review_registration_page.scala.html
There is an issue whereby duplicate IDs are used on the Review Registration screen. `primary-contact-details` is used twice.
This issue is picked up by both Axe and VNU checks.
> PPTP-837 Create a unique HTML id for Organisation details

- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/IncorpIdController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/genericregistration/PartnershipDetails.scala
- tampermonkey/PPT_AutoComplete.js
This is to remain compatible with the back end. Tests checking the mapping between the internal model and that required by EIS were enhanced to check that the partnership name is correctly handled. It is not clear, at this stage, where the partnership name will be captured.
> PPTP-1055 : Added partnership name

- app/uk/gov/hmrc/plasticpackagingtax/registration/connectors/DownstreamServiceError.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewRegistrationController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/Registration.scala
- test/base/unit/MockConnectors.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewRegistrationControllerSpec.scala
In order that the status of the PPT subscription is rendered correctly on the tasklist page, we should never persist the registration as completed. This is not necessary since the registration is deleted once a successful subscription is made.
> PPTP-1038 : Never persist registration as completed

- app/uk/gov/hmrc/plasticpackagingtax/registration/config/Features.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/OrganisationDetailsTypeController.scala
- conf/application.conf
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/OrganisationDetailsTypeControllerSpec.scala
This prevents access to all business types except UK companies, stating to the user that the business type is not yet supported.
> PPTP-1116 : New UK company private beta feature flag

- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/IncorpIdController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewRegistrationController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/OrganisationDetails.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/business_registration_failure_page.scala.html
- conf/messages.en
- test/spec/PptTestData.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/config/ErrorHandlerTest.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/IncorpIdControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/RegistrationControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewRegistrationControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/OrganisationDetailsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/BusinessRegistrationFailureViewSpec.scala
We need to show the user that PPT registration cannot be completed when we are unable to find a business partner id.
Note
Acceptance tests are failing at the moment due to an error which has been introduced in the Sole Trader Identification service. We await a fix for this issue.
> PPTP-1138 : Display Error Page when Business Registration Fails

- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ContactDetailsFullNameController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/forms/FullName.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/PrimaryContactDetails.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/check_primary_contact_details_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/full_name_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/review_registration_page.scala.html
- conf/messages.en
- tampermonkey/PPT_AutoComplete.js
- test/builders/RegistrationBuilder.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ContactDetailsConfirmAddressControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ContactDetailsEmailAddressControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ContactDetailsEmailAddressPasscodeControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ContactDetailsFullNameControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewRegistrationControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/PrimaryContactDetailsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/CheckContactDetailsAnswersViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/ContactDetailsFullNameViewSpec.scala
Change ContactDetails "Who is the primary contact?" page to have single input field for name
Depends on 
- BE change - https://github.com/hmrc/plastic-packaging-tax-registration/pull/51
- AT change - https://github.com/hmrc/plastic-packaging-tax-acceptance/pull/52
> PPT-1087 - Contact details - Amend to single input field

- README.md
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/components/bulletList.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/components/navList.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/start_page.scala.html
- run_local.sh
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/StartViewSpec.scala
Added `aria-labelledby` attribute to `<nav>` as suggested by Axe tool
- renamed `dashList` > `navList` to make intention clearer
- removed `<nav>` from `bulletList` (it's not a navigation element)
- added script to run service locally as I keep forgetting the test routes which cause the ATs to fail
> PPTP-1201 - Nav landmarks not distinguishable on Start Registration screen

- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/actions/AuthAction.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/actions/AuthActionSpec.scala
Check user for presence of `HMRC-PPT-ORG` enrolment and redirect to "accounts" service if found
Requires AT changes - https://github.com/hmrc/plastic-packaging-tax-acceptance/pull/53
> PPTP-1204 - User already subscribed - Redirect users to PPT home

- app/uk/gov/hmrc/plasticpackagingtax/registration/config/AppConfig.scala
Host for PPT accounts FE service is simply `platform.frontend.host` for all MDTP environments.  Only localhost needs to use the value defined in application.config
> PPTP-1204 - fix config for PPT accounts FE service

- app/uk/gov/hmrc/plasticpackagingtax/registration/views/components/link.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/liability_expect_to_exceed_threshold_weight_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/liability_weight_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/not_liable.scala.html
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/LiabilityExpectToExceedThresholdWeightViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/LiabilityWeightViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/NotLiableViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/UnauthorisedViewSpec.scala
- remove `target` attribute from links where not needed
- add `rel="noopener noreferrer"` where target is "_blank" (open in new tab)
> PPTP-1118 - Links vulnerable to reverse tabnabbing

- app/uk/gov/hmrc/plasticpackagingtax/registration/views/address_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/check_liability_details_answers_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/check_primary_contact_details_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/components/link.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/confirm_address.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/confirm_organisation_based_in_uk.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/email_address_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/email_address_passcode_confirmation_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/email_address_passcode_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/full_name_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/job_title_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/liability_expect_to_exceed_threshold_weight_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/liability_liable_date_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/liability_start_date_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/liability_weight_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/main_template.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/not_liable.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/organisation_type.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/partnership_type.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/phone_number_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/review_registration_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/too_many_attempts_passcode_page.scala.html
- build.sbt
- conf/application.conf
- project/AppDependencies.scala
- project/plugins.sbt
- test/base/Stubs.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/audit/AuditorSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/CheckLiabilityDetailsAnswersViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/ReviewRegistrationViewSpec.scala
Update versions in AppDependencies.scala and plugins.sbt
- removed play-frontend-govuk lib (pulled in by play-frontend-hmrc)
Code changes due to 
- removal of static helpers in play-frontend-govuk
- change in auditing message structure
Fixed config warnings
```
2021-09-23 08:16:00,305 level=[WARN] logger=[uk.gov.hmrc.play.bootstrap.config.DeprecatedConfigChecker] thread=[pool-1-thread-1] rid=[] user=[] message=[The key 'play.modules.enabled' is configured with value 'uk.gov.hmrc.play.bootstrap.AuditModule', which is deprecated. Please use 'uk.gov.hmrc.play.audit.AuditModule' instead.] 
2021-09-23 08:16:02,958 level=[WARN] logger=[play.filters.headers.SecurityHeadersConfig] thread=[pool-1-thread-1] rid=[] user=[] message=[play.filters.headers.contentSecurityPolicy is deprecated in 2.7.0. …
```
> PPTP-1210 - Update application library dependencies

- app/uk/gov/hmrc/plasticpackagingtax/registration/config/ErrorHandler.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/actions/AuthAction.scala
- test/base/MockAuthAction.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/config/ErrorHandlerTest.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/actions/AuthActionSpec.scala
Change the way we handle "authorisation" errors to stop them getting logged as exceptions
> BAU - auth error handling

- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ConfirmationController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/SignOutController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/actions/AuthAction.scala
- test/base/MockAuthAction.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ConfirmationControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/SignOutControllerSpec.scala
- solves the potential race condition where subscription request completes before confirmation page is displayed
- creates a second version of AuthAction which does not check enrolments
> PPTP-1204 - allow enrolled user to access confirmation page

- app/uk/gov/hmrc/plasticpackagingtax/registration/views/components/inputText.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/review_registration_page.scala.html
- test/base/unit/UnitViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/ConfirmOrganisationBasedInUkViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/LiabilityExpectToExceedThresholdWeightViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/LiabilityLiableDateViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/OrganisationDetailsTypeViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/PartnershipTypeViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/model/TitleSpec.scala
The `AllMessageKeysAreMandatoryMessages` version of the message api will fail if there is an attempt to translate a message that does not exist in the messages.en file.   Therefore all you need to do it render a view and you don't need tests like this 
```
"have proper messages for labels" in {
messages must haveTranslationFor("organisationDetails.sectionHeader")
messages must haveTranslationFor("organisationDetails.basedInUk.title")
messages must haveTranslationFor("organisationDetails.basedInUk.empty.error")
}
```
In addition, it will detect when a message has been "double translated".   E.g. when a component expects a message key but has been provided with a translated message by the view resulting in the following code - `message(message(key))`
> BAU - use validating message api for tests

- app/uk/gov/hmrc/plasticpackagingtax/registration/connectors/SubscriptionsConnector.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewRegistrationController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/OrganisationDetails.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/subscriptions/SubscriptionCreateResponse.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/components/link.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/components/stackedContentWithLabel.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/duplicate_subscription_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/partials/pptHelplineDetails.scala.html
- build.sbt
- conf/messages.en
- test/base/unit/MockConnectors.scala
- test/spec/PptTestData.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/connectors/SubscriptionsConnectorISpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewRegistrationControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/OrganisationDetailsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/models/subscriptions/SubscriptionCreateResponseSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/DuplicateSubscriptionViewSpec.scala
We need to inform the user of duplicate subscription failures when we attempt to create the PPT subscription. The back end now communicates EIS subscription failure responses so that we can spot failures due to duplicate subscriptions.
Associated BE change: https://github.com/hmrc/plastic-packaging-tax-registration/pull/55
> PPTP-1205 : Alert of Duplicate Subscriptions

- build.sbt
There is a known issue where JUnit reporters can mangle test output files when jobs are run in parallel.
> BAU : Disable the JUnit XML report plugin

- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/IncorpIdController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/RegistrationController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/OrganisationDetails.scala
- test/spec/PptTestData.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/OrganisationDetailsSpec.scala
Two safeIds are modelled in the Organisation domain object. Removed `safeNumber` at the top level and used the embedded registeredBusinessPartnerId for checks on whether a safeId is present or not
> BAU BAU removed unused safe id in domain object so only registeredBusinessPartnerId is used

- app/uk/gov/hmrc/plasticpackagingtax/registration/forms/Address.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/forms/EmailAddress.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/forms/AddressSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/forms/CommonFormValidatorsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/forms/EmailAddressSpec.scala
- Postcode now converted to uppercase before validation
- Email address max length reduced from 241 to 132
> PPTP-1223 Fixed validation rules for email address and postcode

- app/uk/gov/hmrc/plasticpackagingtax/registration/config/ErrorHandler.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/NotableErrorController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewRegistrationController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/error_page.scala.html
- conf/app.routes
- conf/messages.en
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/NotableErrorControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewRegistrationControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/ErrorPageSpec.scala
I think our generic error page content might now have subtly diverged from that of this new discrete subscription failed error page. We might want to work out how we can align these in a future piece of work.
> PPTP-1155 : Discrete error page URL for subscription failures

- app/uk/gov/hmrc/plasticpackagingtax/registration/views/components/continue.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/email_address_passcode_confirmation_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/email_address_passcode_page.scala.html
- conf/app.routes
- conf/messages.en
- tampermonkey/PPT_AutoComplete.js
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/ContactDetailsEmailAddressPasscodeConfirmationViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/ContactDetailsEmailAddressPasscodeViewSpec.scala
I created a continue button component to aid effort for UI consistency
> PPTP-1148 : Email passcode and confirmation page refactor

- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ContactDetailsEmailAddressController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ContactDetailsEmailAddressPasscodeController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/SignedInUser.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/MetaData.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/PrimaryContactDetails.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/Registration.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ContactDetailsEmailAddressPasscodeControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/PrimaryContactDetailsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/RegistrationSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/RegistrationViewSpec.scala
Fixes bug whereby an unverified email address can be submitted if the user by-passes the verification code screen.
"Email verified" is now part of the "Primary Contact Details complete" test
> PPTP-1358 - ensure email is verified before submitting registration

- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/LiabilityController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/NotMembersUnderGroupControlController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/forms/LiabilityExpectedWeight.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/LiabilityDetails.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/Registration.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/NotMembersUnderGroupControlControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/forms/LiabilityExpectedWeightTest.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/LiabilityDetailsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/RegistrationSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/RegistrationGroupViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/RegistrationSingleEntityViewSpec.scala
Prevent access to task list when group not under single control 
- also when not liable according to weight answers
> PPTP-1428 - fix liability and group under single control status logic

- app/uk/gov/hmrc/plasticpackagingtax/registration/config/AppConfig.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/config/AppConfigSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/connectors/grs/GeneralPartnershipGrsConnectorISpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/connectors/grs/ScottishPartnershipGrsConnectorISpec.scala
Update urls as per latest build in https://github.com/hmrc/partnership-identification-frontend
> PPTP-1417 - fix urls for GRS general and scottish partnership journeys

- app/uk/gov/hmrc/plasticpackagingtax/registration/config/AppConfig.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/connectors/addresslookup/AddressLookupFrontendConnector.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/contact/ContactDetailsAddressController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/forms/contact/Address.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/addresslookup/AddressLookupAddress.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/addresslookup/AddressLookupConfigV2.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/addresslookup/AddressLookupConfirmation.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/addresslookup/AddressLookupOnRamp.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/addresslookup/MissingAddressIdException.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/contact/address_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/main_template.scala.html
- conf/app.routes
- conf/application.conf
- conf/messages.en
- test/base/it/ConnectorISpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/connectors/addresslookup/AddressLookupFrontendConnectorISpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/contact/ContactDetailsAddressControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/forms/contact/AddressSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/models/addresslookup/AddressLookupConfirmationSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/ReviewRegistrationViewSpec.scala
Integrate with address lookup frontend to collect contact address
Requires 
Service manager - https://github.com/hmrc/service-manager-config/pull/3956
> PPTP-1243 - initial integration with address lookup frontend

- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/actions/AllowedUsers.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/actions/AllowedUsersSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/actions/AuthActionSpec.scala
Change to case-insensitive check for email address on allow list
> PPTP-1489 - case-insentive allow list checking

- app/uk/gov/hmrc/plasticpackagingtax/registration/views/contact/address_page.scala.html
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/contact/ContactDetailsAddressViewSpec.scala
"Search for another address" link should only be visible when address lookup feature is enabled
Enabled - 
Not Enabled -
> BAU - hide address lookup link when feature not enabled

- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/GroupMemberGrsController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/NotableErrorController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/GroupDetail.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/group/GroupError.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/group/organisation_already_in_group_page.scala.html
- conf/app.routes
- conf/messages.en
- tampermonkey/PPT_AutoComplete.js
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/GroupMemberGrsControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/NotableErrorControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/group/OrganisationAlreadyInGroupViewSpec.scala
Two error pages added
- member is already in group (as a member)
- member is already in group (as nominated org)
Refactored GroupMemberGrsController so that
- problems adding a new member are returned as a Left(GroupError) 
- registration with added member is not saved until it has been verified as valid (will apply to next ticket - member is already subscribed (DUPLICATE_SUBSCRIPTION))
Requires BE change - https://github.com/hmrc/plastic-packaging-tax-registration/pull/101
> PPTP-1432 - Groups - 7B. Errors - Organisation already added to group

- app/uk/gov/hmrc/plasticpackagingtax/registration/config/AppConfig.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/connectors/SubscriptionsConnector.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/actions/AuthAction.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/amendment/AmendRegistrationController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/enrolment/PptEnrolment.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/Registration.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/request/AmendmentJourneyAction.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/request/JourneyAction.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/amendment/amend_registration_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/partials/amendment/primaryContactDetails.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/partials/review/liabilityDetails.scala.html
- conf/app.routes
- conf/messages.en
- test/base/unit/ControllerSpec.scala
- test/base/unit/MockAmendmentJourneyAction.scala
- test/base/unit/MockSubscriptionConnector.scala
- test/spec/PptTestData.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/connectors/SubscriptionsConnectorISpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/actions/AuthActionSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/amendment/AmendRegistrationControllerTest.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/models/request/AmendmentJourneyActionSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/amendment/AmendRegistrationViewSpec.scala
We only display selected data from a previously created registration in part i.
Returns FE: https://github.com/hmrc/plastic-packaging-tax-returns-frontend/pull/97
> PPTP-1540 : Amend Registration - Part I

- app/uk/gov/hmrc/plasticpackagingtax/registration/config/AppConfig.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/connectors/addresslookup/AddressLookupFrontendConnector.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/connectors/grs/SoleTraderGrsConnector.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/genericregistration/SoleTraderGrsCreateRequest.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/config/AppConfigSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/connectors/grs/SoleTraderIncorpIdConnectorISpec.scala
Also removed logging call which is no longer needed.
> PPTP-1572 : Fix Sole Trader GRS Integration

- app/uk/gov/hmrc/plasticpackagingtax/registration/connectors/addresslookup/AddressLookupFrontendConnector.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/NotableErrorController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/contact/ContactDetailsAddressController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/OrganisationDetailsTypeHelper.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/organisation/GrsController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/organisation/sole_trader_verification_failure_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/partials/selfAssessmentHelplineDetails.scala.html
- conf/app.routes
- conf/messages.en
- test/builders/RegistrationBuilder.scala
- test/spec/PptTestData.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/NotableErrorControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/organisation/CheckAnswersControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/organisation/GrsControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/repositories/UserDataRepositorySpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/organisation/SoleTraderVerificationFailureViewSpec.scala
Add a specific failure page for Sole traders returning from a failed GRS journey.
Sole Traders are challenged with questions about their Self Assessment history so this screen should prompt them to contact Self Assessment.
Log output for a Sole Trader returning from GRS after entering incorrect Business Verification Self Assessment answers 5 times:
```
logger=[uk.gov.hmrc.plasticpackagingtax.registration.controllers.organisation.GrsController]
message=[PPT GRS callback for journeyId [33e7eae0-2fbb-4c43-9659-3f26013299b2]
and organisation type [SoleTrader] had registration status [SOLE_TRADER_VERIFICATION_FAILED]
and details [RegistrationDetails(true,Some(FAIL),REGISTRATION_NOT_CALLED,None)]]
```
> PPTP 1286 - Sole Trader custom registration failed error page

- app/uk/gov/hmrc/plasticpackagingtax/registration/forms/organisation/PartnerType.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/genericregistration/Partner.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/genericregistration/PartnerContactDetails.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/genericregistration/PartnershipDetails.scala
BE PR: https://github.com/hmrc/plastic-packaging-tax-registration/pull/119
> PPTP-1595 : Registration Model Update to Support Partnerships

- tampermonkey/PPT_AutoComplete.js
Modified the month input from `06` to `04` on the `/register-for-plastic-packaging-tax/liable-date` page.
Mfw the Tampermonkey script hits this page for the 87th time in a day:
> BAU: Update Tampermonkey script

- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/amendment/AmendEmailAddressController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/contact/ContactDetailsEmailAddressController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/contact/ContactDetailsEmailAddressPasscodeController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/Registration.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/services/EmailVerificationService.scala
- test/base/unit/MockConnectors.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/amendment/AmendEmailAddressControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/contact/ContactDetailsEmailAddressControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/contact/ContactDetailsEmailAddressPasscodeControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/services/EmailVerificationServiceSpec.scala
Rationalise our implementations on email verification by doubling down in the recent `EmailVerficationService`.
Motivation; we're about to add a 3rd usage of email verification.
> Deduplicate direct usages of EmailVerficationConnector to use EmailVerificationService

- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerContactNameController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerGRSRedirections.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerGrsController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerNameController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerTypeController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnershipTypeController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/forms/partner/PartnerName.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/genericregistration/Partner.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/genericregistration/PartnershipDetails.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/services/GRSRedirections.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/partner/partner_check_answers_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/partner/partner_name_page.scala.html
- conf/app.routes
- conf/messages.en
- test/spec/PptTestData.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerContactNameControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerEmailAddressControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerGrsControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerNameControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerPhoneNumberControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerTypeControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnershipTypeControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/models/genericregistration/PartnershipDetailsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/partner/PartnerCheckAnswersViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/partner/PartnerNamePageViewSpec.scala
For Partnership Partner types who GRS does not supply a name for, prompt the user for a user supplied name instead.
This happens after the user selects a partner type and before the GRS journey.
Do not do this for partners (like UK companies) who we know GRS will supply a name for.
Users should not be able to use this functionality to override a GRS supplied name.
GRS redirects deduplicated into a trait in services, on their way to been a full service one day.
trait defers the need to update all the tests in this PR.
> PPTP-1642 Prompt for user supplied names for Partner types which GRS does not supply names for

- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerGrsController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerNameController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerTypeController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnershipTypeController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/forms/organisation/PartnerType.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/genericregistration/Partner.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/genericregistration/PartnershipDetails.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/OrganisationDetails.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/partials/review/partnerDetail.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/partner/partner_check_answers_page.scala.html
- test/spec/PptTestData.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerGrsControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/models/genericregistration/PartnershipDetailsSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/ReviewRegistrationViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/partner/PartnerCheckAnswersViewSpec.scala
Clarify our understanding of how Partner type is recorded.
- Remove unused Partner.partnerPartnershipDetails.partnershipType
- Make Partner.partnershipType mandatory.
Partner type is the first thing we ask when setting up an inflight Partner; partners do not existing without this field.
Remove alot of Some wrapping around this value.
The backend can keep this field as an Optional if it wants but should be aware that we will always set it going forward (probably always have done as well).
> Clarify partner type fields

- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerContactNameController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerJobTitleController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/genericregistration/PartnerContactDetails.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/partner/partner_check_answers_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/partner/partner_job_title_page.scala.html
- conf/app.routes
- conf/messages.en
- test/spec/PptTestData.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerContactNameControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerJobTitleControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/partner/PartnerCheckAnswersViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/partner/PartnerJobTitlePageViewSpec.scala
Nominated partners (or the first in flight partner been added) are prompted for the contact's job title.
Check answers page renders the job title if it is present.
Any partner whom we hold a job title for has the option to edit it (guards against partner moving around; been promoted or demoted from been the nominated partner)
Known limitations - the back link from content email address still links to contact name.
> PPTP-1664 Prompt nominated partners for job title

- app/uk/gov/hmrc/plasticpackagingtax/registration/views/amendment/amend_registration_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/components/linkButton.scala.html
- conf/messages.en
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/amendment/AmendRegistrationViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/components/LinkButtonSpec.scala
Adding "Return to account" button to organisation details page
> PPTP-1426 Adding "Return to account" button to organisation details page

- conf/messages.en
Spotted that titles are auto suffixed with the PPT - GOV stuff. 
This removes the duplication.
> Correct titles for auto suffixing

- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/address/AddressCaptureController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/forms/contact/Address.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/address/AddressCaptureControllerSpec.scala
The standard form fillAndValidate() call was not spotting missing postcodes for UK addresses entered via ALF. I suspect this was connected to our use of a mandatoryIfEqual mapping validator. This is a work-around to bypass this shortcoming.
> PPTP-1732 : Trap ALF Addresses with Missing Postcodes

- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/StartRegistrationController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/TaskListController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/liability/BackwardLookTestController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/liability/RegistrationTypeController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/liability/prelaunch/LiabilityWeightExpectedController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/liability/prelaunch/liability_weight_expected_page.scala.html
- conf/app.routes
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/StartTaskListControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/TaskListControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/liability/LiabilityWeightExpectedControllerTest.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/liability/RegistrationTypeControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/liability/LiabilityExpectedWeightViewSpec.scala
…laceholder url and controller for backwards-look test
Move pre-launch liability controller and view to own package, add placeholder url and controller for backwards-look test
> Move pre-launch liability controller and view to own package

- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/EmailVerificationActions.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/amendment/AmendEmailAddressController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/amendment/partner/AddPartnerContactDetailsEmailAddressController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/amendment/partner/AmendPartnerContactDetailsController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/contact/ContactDetailsEmailAddressController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/contact/ContactDetailsEmailAddressPasscodeConfirmationController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/contact/ContactDetailsEmailAddressPasscodeController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerEmailAddressController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerEmailAddressControllerBase.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/testOnly/EmailPasscodeController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/PrimaryContactDetails.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/Registration.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/contact/email_address_passcode_confirmation_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/contact/email_address_passcode_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/partials/review/partnerDetail.scala.html
- conf/app.routes
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/amendment/AmendEmailAddressControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/amendment/partner/AmendPartnerContactDetailsControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/contact/ContactDetailsEmailAddressPasscodeConfirmationControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/contact/ContactDetailsEmailAddressPasscodeControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerEmailAddressControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/testOnly/EmailPasscodeControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/contact/ContactDetailsEmailAddressPasscodeConfirmationViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/contact/ContactDetailsEmailAddressPasscodeViewSpec.scala
Starting with `AmendEmailAddressController.scala` as the best pre existing example of an email verification flow, 
we have stripped it for parts and collected the common actions in `EmailVerificationActions`.
As partner email verification applies to registrations and amendments we need away of persisting email verification journey data which will work from registration and amendment journeys.
The lowest common denominator seems to be `RegistrationUpdater`. 
The side effects of using this are that backend registration needs to persist the emali verification prospective email address and journey id on the mongo registration. Amendments are probably making a full EMTP submission when storing the prospective email. Both of these are side effects of choosing to use the Registration so store …
> PPTP 1636 Nominated partners must validate their email addresses

- project/AppDependencies.scala
Upgrading the `play-frontend-hmrc` library following guidance in the [accessibility test report](https://build.tax.service.gov.uk/job/Plastic%20Packaging%20Tax/job/plastic-packaging-tax-a11y-tests/40/Accessibility_20Check_20Report/) to resolve issues identified by VNU.
> Upgrade library to resolve accessibility issues

- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewRegistrationController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/actions/AuthAction.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/request/AuthenticatedRequest.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/request/JourneyRequest.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/response/FlashKeys.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/confirmation_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/utils/ViewUtils.scala
- conf/messages.en
- test/base/unit/ControllerSpec.scala
- test/spec/PptTestData.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/KeepAliveControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewTaskListControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/address/AddressCaptureControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/models/request/AmendmentJourneyActionSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/repositories/MongoRegistrationAmendmentRepositorySpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/repositories/UserDataRepositorySpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/repositories/UserEnrolmentDetailsRepositorySpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/services/AddressCaptureServiceSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/ConfirmationViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/ReviewRegistrationViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/address/AddressViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/liability/CheckLiabilityDetailsAnswersViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/organisation/CheckAnswersPageViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/organisation/PartnershipPartnerTypeViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/partials/PhaseBannerSpec.scala
Access to feature flag state migrated from JourneyRequest to AuthenticatedRequest. This was necessary since we do not want to use JourneyAction in the confirmation controller as we do not want a shell registration creating. This had a knock-on effect in a lot of tests which were creating AuthenticatedRequests and JourneyRequests.
WAVE does report a single warning but this is due to close links having the same target. I'm guessing the content folks are aware and happy with it.
> PPTP-1756 : Rework Registration Submitted Confirmation Page

- app/uk/gov/hmrc/plasticpackagingtax/registration/views/contact/phone_number_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/group/member_phone_number_page.scala.html
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/contact/ContactDetailsPhoneNumberViewSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/group/ContactDetailsPhoneNumberViewSpec.scala
Label wasn't rendering interpolated values correctly
> Fixed hidden label so it contains contact name

- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/actions/AuthAction.scala
- test/base/PptTestData.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/actions/AuthActionSpec.scala
Adjust the registration auth action to prevent Agents from accidentally registering themselves; block them from all registration journey screens.
Adjust the amendment auth action to send Agents who have not identified their client back to returns. The returns UI will prompt them todo this and land them back on the account page.
> Restrict agents from registration journey

- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/actions/AuthAction.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/actions/AuthActionSpec.scala
Same change as applied to Returns.
> PPTP-1854 Agents are allowed into amend screens with weak credentials

- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/actions/AuthAction.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/actions/AuthActionSpec.scala
Users hitting amendment screens with no enrolments are bounced back to Returns and ultimately the not enrolled screen.
Returns not enrolled prompts unregistered normal users to register and prompts agents to select a client.
> PPTP-1854 Users hitting amendment screens with no enrolments are bounced back to Returns

- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/liability/CheckLiabilityDetailsAnswersController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/Registration.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/liability/CheckLiabilityDetailsAnswersControllerTest.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/RegistrationSpec.scala
The completeness of the Liability Details task list section needs to check if the registration type has been completed.
> PPTP-1910 Task list liability details step is not completed until a registration type has been entered

- app/uk/gov/hmrc/plasticpackagingtax/registration/views/components/saveButtons.scala.html
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/components/SaveButtonsSpec.scala
Removing save and come back later from views.
Note - full removal of component will be carried out as part of https://jira.tools.tax.service.gov.uk/browse/PPTP-1917
> PPTP-1911 - Removing save and come back later button from views

- app/uk/gov/hmrc/plasticpackagingtax/registration/views/liability/check_liability_details_answers_page.scala.html
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/liability/CheckLiabilityDetailsAnswersViewSpec.scala
This click does nothing; the save has already happened.
Confirm and continue was another suggestion but it's not currently used anywhere in Registration.
Continue is also consistent with the your tax date confirm screen which proceeds this screen.
> PPTP-1915 Continue is a more accurate label for the check liability page action

- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewRegistrationController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/services/RegistrationGroupFilterService.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewTaskListControllerSpec.scala
- Adding guard to check entity is group and contains multiple members
- Removing group details if entity is not Group.
TODO - add unit tests when single entity contains groupDetails
> PPTP-1949 - Removing group details from single entity

- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerContactNameControllerBase.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerGrsControllerBase.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/services/CountryService.scala
- conf/resources/countrySynonyms.json
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewTaskListControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/GroupMemberGrsControllerSpec.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/services/CountryServiceSpec.scala
Logic to try to find country code from synonyms resource if an invalid FCO country name received from GRS.
Tidied a few warnings as well.
> Country code lookup by synonym

- app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/ConfirmBusinessAddressController.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/utils/URLSanitisationUtils.scala
- test/uk/gov/hmrc/plasticpackagingtax/registration/utils/URLSanitisationUtilsSpec.scala
Convert redirectTo addresses to relative urls to prevent url hijacking on callback from ALF with redirectTo.
> Sanitise redirectTo address for group member ALF callback

- conf/application.conf
url must differ for reg and returns as they have their own respective a11y statements
> Registation a11y statement config updated

- app/uk/gov/hmrc/plasticpackagingtax/registration/views/components/errorSummary.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/liability/exceeded_threshold_weight_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/liability/expect_to_exceed_threshold_weight_page.scala.html
- conf/messages.en
1. Fixed error summary links to take focus to  the date entry
2. Stopped empty links from being in the error summary
3. Fixed a type on a message
> PPTP-2391: Fixed threshold date error links

- app/uk/gov/hmrc/plasticpackagingtax/registration/forms/liability/ExceededThresholdWeight.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/forms/liability/ExpectToExceedThresholdWeight.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/forms/mappings/Formatters.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/forms/mappings/LocalDateFormatter.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/forms/mappings/Mappings.scala
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/address/uk_address_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/components/conditionalYesNoRadio.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/components/errorSummary.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/liability/exceeded_threshold_weight_page.scala.html
- app/uk/gov/hmrc/plasticpackagingtax/registration/views/liability/expect_to_exceed_threshold_weight_page.scala.html
- test/uk/gov/hmrc/plasticpackagingtax/registration/views/liability/ExpectToExceedThresholdWeightViewSpec.scala
1. Fixed error summary links on various pages for the various error keys seen
2. Prevented yes / no missing answer error from being shown on the expandable date field
3. Added a missing error summary
4. Simplified boolean mapping logic
> PPTP-2391b: More error link fixes

- conf/application.conf
- project/build.properties
- project/plugins.sbt
SBT can be updated to 1.7.2 in [project/build.properties](https://github.com/hmrc/plastic-packaging-tax-registration-frontend/blob/repackage/project/build.properties#L1)
uk.gov.hmrc.sbt-auto-build can be updated to 3.8.0 in [project/plugins.sbt](https://github.com/hmrc/plastic-packaging-tax-registration-frontend/blob/repackage/project/plugins.sbt#L8)
Runtime issues may occur. Change com.typesafe.play.sbt-plugin to 2.8.8 in [project/plugins.sbt](https://github.com/hmrc/plastic-packaging-tax-registration-frontend/blob/repackage/project/plugins.sbt#L14) - to match what uk.gov.hmrc.play-frontend-hmrc uses
Deprecated config key session.maxAge can be changed to play.http.session.maxAge in [conf/application.conf](https://github.com/hmrc/plastic-packaging-tax-registration-frontend/blob/repackage/c …
> pr suggested updates

- app/models/request/AuthenticatedRequest.scala
- app/repositories/UserDataRepository.scala
While ideally this would be the cache ID to stop agents from potentially having answers leak from one client to another, the way its been built this is endpoint is used by both registrations and amends and is non trivial to divide. Changing to internalID will be used the same by both user types and the document will be found regardless of which auth action you have come through
> Switch to internal ID
