hmrc/plastic-packaging-tax-registration-frontend

app/uk/gov/hmrc/plasticpackagingtax/registration/views/main_template.scala.html, build.sbt, conf/messages.en, project/AppDependencies.scala, test/base/Injector.scala, test/spec/UnitViewSpec.scala, test/spec/ViewMatchers.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/HelloWorldControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/FooterViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/model/TitleSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/tags/ViewTest.java, test/utils/FakeRequestCSRFSupport.scala
Instead of creating our own footer items we should instead load the
default list of the HMRC.
This also updates the GovUK/HMRC Play FE dependencies.
=> PPTP-280 Dynamically load the footer items

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/HonestyDeclarationController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/LiabilityStartDateController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/StartController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/forms/Date.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/forms/LiabilityStartDate.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/components/bulletList.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/components/dashList.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/components/pageTitle.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/error_template.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/honesty_declaration.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/liability_start_date_page.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/main_template.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/partials/phaseBanner.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/registration_page.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/start_page.scala.html, conf/app.routes, conf/messages.en, test/base/it/ConnectorISpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/LiabilityStartDateControllerTest.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/forms/LiabilityStartDateSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/LiabilityStartDateViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/RegistrationViewSpec.scala
Liability start page for reg journey. 
Outstanding work include preserving date provided by user and  update task status on reg page.
=> Feature/PPTP-314 - Liability start date page

app/uk/gov/hmrc/plasticpackagingtax/registration/connectors/RegistrationConnector.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/LiabilityStartDateController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/LiabilityWeightController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/Cacheable.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/LiabilityDetails.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/Registration.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/request/JourneyAction.scala, build.sbt, conf/messages.en, test/base/unit/ControllerSpec.scala, test/base/unit/MockJourneyAction.scala, test/base/unit/MockRegistrationConnector.scala, test/base/unit/UnitViewSpec.scala, test/builders/RegistrationBuilder.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/connectors/RegistrationConnectorSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/LiabilityStartDateControllerTest.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/LiabilityWeightControllerTest.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/models/request/JourneyActionSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/LiabilityStartDateViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/LiabilityWeightViewSpec.scala
**Work involved:**
* [Save Liability Details](https://github.com/hmrc/plastic-packaging-tax-registration-frontend/pull/16/commits/9f186368632f2b5fc6d0308204a523deeb33c768)
* [Rehydrate Liability forms with data](https://github.com/hmrc/plastic-packaging-tax-registration-frontend/pull/16/commits/28de29e370a6b0cf724229e9a6d458d1c54366a9)
* [Increase code coverage threshold to 90%](https://github.com/hmrc/plastic-packaging-tax-registration-frontend/pull/16/commits/4723ae33e7061175be54fcce34a23773eb2c0a88)
=> PPTP-332 Save Liability Details

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/RegistrationController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/LiabilityDetails.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/model/TaskStatus.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/registration_page.scala.html, build.sbt, conf/messages.en, test/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/LiabilityDetailsSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/RegistrationViewSpec.scala
Work Includes:
* [Dynamically drive task list statuses](https://github.com/hmrc/plastic-packaging-tax-registration-frontend/pull/18/commits/21f7bd07a59f602cf59b3439816bacb759d1f4b2)
* [Increase code coverage to 91%](https://github.com/hmrc/plastic-packaging-tax-registration-frontend/pull/18/commits/0e7c61401baf4f0e9e21f7aa19d1cba6be4a4e0a)
=> PPTP-391 Dynamically Load task list statuses

app/uk/gov/hmrc/plasticpackagingtax/registration/views/components/errorSummary.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/liability_start_date_page.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/liability_weight_page.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/registration_page.scala.html, build.sbt, conf/messages.en, test/uk/gov/hmrc/plasticpackagingtax/registration/views/LiabilityStartDateViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/LiabilityWeightViewSpec.scala
**Work includes:**
* Change 'In Progress' tag colour
* BAU - Add error summary and test coverage
* BAU - Fix Error Summary Links
* BAU - Increase code coverage to 93%
=> PPTP-391 Change 'In Progress' tag colour

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ContactDetailsAddressController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ContactDetailsCheckAnswersController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/check_primary_contact_details_page.scala.html, conf/app.routes, conf/messages.en, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ContactDetailsAddressControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ContactDetailsCheckAnswersControllerTest.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/CheckContactDetailsAnswersViewSpec.scala
=> PPTP-435 Primary contact details check your answers page

app/uk/gov/hmrc/plasticpackagingtax/registration/config/AppConfig.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/connectors/IncorpIdConnector.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewRegistrationController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/genericregistration/IncorporationDetails.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/Registration.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/registration_page.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/review_registration_page.scala.html, conf/app.routes, conf/messages.en, tampermonkey/PPT_AutoComplete.js, test/builders/RegistrationBuilder.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/connectors/IncorpIdConnectorISpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewRegistrationControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/RegistrationSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/RegistrationViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/ReviewRegistrationViewSpec.scala
**Work Includes:**
* Review Registration page
* Add Review Registration autocomplete
* Get Details from Generic Registration Service
=> PPTP-353 Add Review Registration page

conf/application.conf
This is required in order to submit GTM tags
=> PPTP-498 Add Content Security Policy required domains

README.md, app/uk/gov/hmrc/plasticpackagingtax/registration/connectors/IncorpIdConnector.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/connectors/RegistrationConnector.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/actions/AuthAction.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/check_liability_details_answers_page.scala.html, tampermonkey/PPT_Auth_AutoComplete.js
**Work undertaken:**
* Change PPT Auth Enrolment Key
* BAU - Update dependencies
* BAU - Clear compilation warnings
=> PPTP-542 Change PPT Auth Enrolment Key

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ContactDetailsConfirmAddressController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/forms/CommonFormValidators.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/forms/ConfirmAddress.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/genericregistration/IncorporationAddressDetails.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/genericregistration/IncorporationDetails.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/PrimaryContactDetails.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/address_page.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/check_primary_contact_details_page.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/confirm_address.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/review_registration_page.scala.html, conf/app.routes, conf/messages.en, tampermonkey/PPT_AutoComplete.js, test/base/it/ConnectorISpec.scala, test/base/unit/ControllerSpec.scala, test/base/unit/UnitViewSpec.scala, test/spec/PptTestData.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/connectors/IncorpIdConnectorISpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ContactDetailsConfirmAddressControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ContactDetailsTelephoneNumberControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewRegistrationControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/forms/ConfirmAddressSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/models/genericregistration/IncorporationAddressDetailsSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/CheckContactDetailsAnswersViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/ContactDetailsAddressViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/ContactDetailsConfirmAddressViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/ReviewRegistrationViewSpec.scala
=> PPTP-433 Add confirm address page

app/uk/gov/hmrc/plasticpackagingtax/registration/audit/Auditor.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/audit/CreateRegistrationEvent.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewRegistrationController.scala, conf/application.conf, test/base/unit/ControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/audit/AuditorSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewRegistrationControllerSpec.scala
There is one TODO  in submission controller, this needs to be re-done in order to guarantee consistency and sequence of calls on success and failure. This implementation is only initial happy path integration, to be refactored once EIS submission will be integrated.
=> PPTP-739: initial txm integration

app/uk/gov/hmrc/plasticpackagingtax/registration/config/AppConfig.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/connectors/SubscriptionsConnector.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/IncorpIdController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewRegistrationController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/OrganisationDetails.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/subscriptions/SubscriptionCreateResponse.scala, test/base/it/ConnectorISpec.scala, test/base/unit/MockConnectors.scala, test/spec/PptTestData.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/config/AppConfigSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/connectors/SubscriptionsConnectorISpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewRegistrationControllerSpec.scala
A subsequent ticket and commit will be required to clean up the code
where we store the `safeNumber` and to minimize the number of calls to
GRS.
=> PPTP-858 Submit a PPT Subscription request to EIS

app/uk/gov/hmrc/plasticpackagingtax/registration/models/genericregistration/IncorporationDetails.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/genericregistration/SoleTraderIncorpIdCreateRequest.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/genericregistration/SoleTraderIncorporationDetails.scala, tampermonkey/PPT_AutoComplete.js, test/spec/PptTestData.scala
* Reintroduce the company name for UK Limited companies. This seems to
have been a bug.
* Support Sole Traders journey, so that the `sautr` flag is always set
to true, so that we can enable SAUTR checks and register the entity
=> PPTP-360 Add support for Sole Traders

app/uk/gov/hmrc/plasticpackagingtax/registration/connectors/RegistrationConnector.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewRegistrationController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/Registration.scala, test/builders/RegistrationBuilder.scala
These should only be set when confirming the Check your answers page.
=> PPTP-757 Make userHeaders optional

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ContactDetailsConfirmAddressController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewRegistrationController.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ContactDetailsConfirmAddressControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewRegistrationControllerSpec.scala
- This is to reduce the calls to GRS and get the company details from registration DB.
=> PPTP-887 Company details from our DB

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewRegistrationController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/nrs/NrsDetails.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/MetaData.scala, test/spec/PptTestData.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewRegistrationControllerSpec.scala
As part of the NRS work we are expected to audit the NRS SubmissionId
or the NRS failure reason.
=> PPTP-994 Audit NRS Submission response

app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/Registration.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/registration_page.scala.html, conf/messages.en, test/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/RegistrationSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/RegistrationViewSpec.scala
This also meant enabling the link for that section, as it will be the
first section the user will see in the new PPT prototype version.
=> PPTP-1019 Reorder Liability Details on Registration page

app/uk/gov/hmrc/plasticpackagingtax/registration/views/check_liability_details_answers_page.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/review_registration_page.scala.html, test/uk/gov/hmrc/plasticpackagingtax/registration/views/CheckLiabilityDetailsAnswersViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/ReviewRegistrationViewSpec.scala
- Update the review registration page to display Liability section with expect to exceed threshold weight and liable for plastic packaging tax before 1 April 2022 question
- Liability section display moved to the top in the review registration page.
=> PPTP-1022 Update Review Registration page

app/uk/gov/hmrc/plasticpackagingtax/registration/views/review_registration_page.scala.html, conf/messages.en
- Changed the heading for Liability section
=> PPTP-1022 Review changes

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/LiabilityWeightController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/forms/LiabilityWeight.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/LiabilityWeightControllerTest.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/forms/LiabilityWeightTest.scala
=> PPTP-1080 Change de minimis to 10000

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/helpers/LiabilityLinkHelper.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/OrganisationDetailsTypeControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/helpers/LiabilityLinkHelperSpec.scala
=> PPTP-1097 Fixed back link from still liable page

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ContactDetailsAddressController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ContactDetailsConfirmAddressController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ContactDetailsEmailAddressPasscodeController.scala
=> PPTP-1098 Fixed address not being populated on change.

README.md, conf/testOnlyDoNotUseInAppConf.routes, tampermonkey/PPT_AutoComplete.js
- update README to fix instructions for logging in and running the service with test-only routes
- update TamperMonkey script to handle multiple email passcodes returned from the verification end-point
=> BAU - documentation fixes

app/uk/gov/hmrc/plasticpackagingtax/registration/audit/CreateRegistrationEvent.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/audit/StartRegistrationEvent.scala
=> PPTP-1114 Changed audit type name.

app/uk/gov/hmrc/plasticpackagingtax/registration/views/email_address_passcode_confirmation_page.scala.html
H1 isn't a label for anything, so removed the label element
=> PPTP-1202 - Value of "for" attribute on "label" is the ID of a hidden form control

tampermonkey/PPT_Auth_AutoComplete.js
- do not fill in PPT enrolment when logging into registration service
=> BAU - auth loging TamperMonkey script

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/IncorpIdController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/genericregistration/IncorporationDetails.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/OrganisationDetails.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/business_verification_failure_page.scala.html, conf/application.conf, conf/messages.en, test/builders/RegistrationBuilder.scala, test/spec/PptTestData.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/IncorpIdControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewRegistrationControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/OrganisationDetailsSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/BusinessVerificationFailureViewSpec.scala
- Added the skeleton page for Business Verification Failure
- Content of the page - TBC
=> PPTP-1072 Added business verification failure page

tampermonkey/PPT_Auth_AutoComplete.js
Update `Quick Submit` button in Tampermonkey scripts and bump the file version.
Solution provided by @SteveSugden: https://hmrcdigital.slack.com/archives/G01PR65H61W/p1632299076040300
=> BAU: Update Quick Submit button Tampermonkey script

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/IncorpIdController.scala
Refactor code to remove Future[Future]
=> BAU - refactor to remove Future[Future[....]] structures

app/uk/gov/hmrc/plasticpackagingtax/registration/models/subscriptions/ETMPSubscriptionChannel.scala, test/spec/PptTestData.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/RegistrationControllerSpec.scala
Added channel to subscription status response
=> PPTP-1209 Updated Get Subscription Status (API 1534) to v2.2.0

app/uk/gov/hmrc/plasticpackagingtax/registration/models/request/IdentityData.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/BusinessRegistrationFailureViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/BusinessVerificationFailureViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/ConfirmationViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/LiabilityExpectToExceedThresholdWeightViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/OrganisationDetailsTypeViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/OrganisationTypeNotSupportedViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/PartnershipTypeViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/RegistrationViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/SessionTimedOutViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/StartViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/TooManyAttemptsPasscodeViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/UnauthorisedViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/partials/PhaseBannerSpec.scala
- Removed some unused code
- Add calls to generated "render" view methods
Coverage now approx. 96.8%
=> BAU - improve code coverage

app/uk/gov/hmrc/plasticpackagingtax/registration/views/job_title_page.scala.html, conf/app.routes, conf/messages.en, tampermonkey/PPT_AutoComplete.js, test/uk/gov/hmrc/plasticpackagingtax/registration/views/ContactDetailsJobTitleViewSpec.scala
Update primary contact job title page
- url change to /main....
- include contact name in title & heading
- update section heading
=> PPTP-1217 - Input business contact - Job Title

app/uk/gov/hmrc/plasticpackagingtax/registration/views/components/sectionHeader.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/full_name_page.scala.html, conf/app.routes, conf/messages.en, tampermonkey/PPT_AutoComplete.js, test/uk/gov/hmrc/plasticpackagingtax/registration/views/ContactDetailsAddressViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/ContactDetailsConfirmAddressViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/ContactDetailsEmailAddressPasscodeConfirmationViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/ContactDetailsEmailAddressPasscodeViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/ContactDetailsEmailAddressViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/ContactDetailsFullNameViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/ContactDetailsJobTitleViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/ContactDetailsPhoneNumberViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/LiabilityExpectToExceedThresholdWeightViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/LiabilityLiableDateViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/LiabilityStartDateViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/LiabilityWeightViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/OrganisationDetailsTypeViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/PartnershipTypeViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/TooManyAttemptsPasscodeViewSpec.scala
changed url to /main-contact-name
replaced the word primary in text with main
section-header style reduced from xl to l
=> Primary contact name changed to main contact name

app/uk/gov/hmrc/plasticpackagingtax/registration/views/main_template.scala.html
=> BAU - beta banner

app/uk/gov/hmrc/plasticpackagingtax/registration/views/phone_number_page.scala.html, conf/app.routes, conf/messages.en, tampermonkey/PPT_AutoComplete.js, test/uk/gov/hmrc/plasticpackagingtax/registration/views/ContactDetailsPhoneNumberViewSpec.scala
=> PPTP-1219 - Input business contact - Phone number

app/uk/gov/hmrc/plasticpackagingtax/registration/views/check_primary_contact_details_page.scala.html, conf/app.routes, conf/messages.en, tampermonkey/PPT_AutoComplete.js, test/uk/gov/hmrc/plasticpackagingtax/registration/views/CheckContactDetailsAnswersViewSpec.scala
=> PPTP-1227 Contact Details - Check your answers

app/uk/gov/hmrc/plasticpackagingtax/registration/forms/CommonFormValidators.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/forms/PhoneNumber.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/forms/CommonFormValidatorsSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/forms/PhoneNumberSpec.scala
=> PPTP-1224 - Fixed phone number validation

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/GrsController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/NotableErrorController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/business_verification_failure_page.scala.html, conf/app.routes, conf/messages.en, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/GrsControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/NotableErrorControllerSpec.scala
- Updated content of `business_verification_page`
- Changed implementation in GrsController to redirect to new url
- [x ] User Acceptance Tests (UAT) were run locally and have passed.
=> PPTP-1256 - ERROR PAGE - 3. Business Verification failed

conf/messages.en
=> PPTP-1268 - ERROR PAGE - Registration failed

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/NotableErrorController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/RegistrationController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewRegistrationController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/duplicate_subscription_page.scala.html, conf/app.routes, conf/messages.en, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/NotableErrorControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/RegistrationControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewRegistrationControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/DuplicateSubscriptionViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/partials/PptHelplineDetailsSpec.scala
=> PPTP-1250 : Discrete URL for Duplicate Subscriptions

test/base/unit/MockRegistrationConnector.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ConfirmationControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ContactDetailsAddressControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ContactDetailsCheckAnswersControllerTest.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ContactDetailsConfirmAddressControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ContactDetailsEmailAddressControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ContactDetailsEmailAddressPasscodeConfirmationControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ContactDetailsEmailAddressPasscodeControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ContactDetailsFullNameControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ContactDetailsJobTitleControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ContactDetailsTelephoneNumberControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/LiabilityExpectToExceedThresholdWeightControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/LiabilityStartDateControllerTest.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/LiabilityWeightControllerTest.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/LiabilityWeightExpectedControllerTest.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/OrganisationDetailsTypeControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/PartnershipTypeControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewRegistrationControllerSpec.scala
=> BAU-removed-deprecated-method Removed deprecated method

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ContactDetailsAddressController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ContactDetailsEmailAddressController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ContactDetailsEmailAddressPasscodeController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ContactDetailsTelephoneNumberController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/emailverification/EmailVerification.scala
=> BAU - remove println statements

app/uk/gov/hmrc/plasticpackagingtax/registration/forms/enrolment/PptReference.scala
=> Updated PPT reference regex

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ContactDetailsEmailAddressController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewRegistrationController.scala
- remove redundant check for safeId
- unused import
=> BAU - code tidy

app/uk/gov/hmrc/plasticpackagingtax/registration/config/Features.scala, conf/application.conf
=> PPTP-1391 : Group registration feature switch

app/uk/gov/hmrc/plasticpackagingtax/registration/connectors/SubscriptionsConnector.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/connectors/enrolment/UserEnrolmentConnector.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/connectors/grs/GrsConnector.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/GrsController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/OrganisationDetails.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ContactDetailsEmailAddressPasscodeControllerSpec.scala
- manual user enrolment response
- get subscription status response
- submit subscription response
=> PPTP-1379 - additional info level logging

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/OrganisationDetailsTypeController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/forms/OrganisationType.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/organisation_type.scala.html, conf/messages.en, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ContactDetailsConfirmAddressControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/OrganisationDetailsTypeControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/forms/OrganisationTypeSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/OrganisationDetailsSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/OrganisationDetailsTypeViewSpec.scala
- Updated content on page
- Renamed/created new org type enum value
Needs BE PR - https://github.com/hmrc/plastic-packaging-tax-registration/pull/85
=> PPTP-1162 - Update 'What is your organisation type' page

app/uk/gov/hmrc/plasticpackagingtax/registration/forms/RegistrationType.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/GroupDetail.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/Registration.scala
Added registration type (group or single entity) and group detail to Registration.
=> PPTP-13381 : Registration type and group detail

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/OrganisationDetailsTypeController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/forms/OrganisationType.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/organisation_type.scala.html, conf/messages.en, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/OrganisationDetailsTypeControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/OrganisationDetailsTypeViewSpec.scala
=> PPTP-1185 - Select Nominated Organisation

test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/OrganisationListControllerSpec.scala
Re-organise controller spec into "display" and "submit" sections
=> PPTP-1187 - re-organise OrganisationListControllerSpec

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewRegistrationController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/partials/review/liabilityDetails.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/partials/review/organisationDetails.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/partials/review/primaryContactDetails.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/review_registration_page.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/utils/ViewUtils.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewRegistrationControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/ReviewRegistrationViewSpec.scala
* Pulled each section into its own partial
* Extracted helper methods into a new ViewUtils object
=> PPTP-1418 : Refactor registration review page

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/GroupMemberGrsController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/OrganisationDetailsTypeController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/genericregistration/IncorporationDetails.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/GroupDetail.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/Registration.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/group/GroupMember.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/group/OrganisationDetails.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/group/organisation_type.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/partials/review/liabilityDetails.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/partials/review/organisationDetails.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/partials/review/primaryContactDetails.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/review_registration_page.scala.html, conf/messages.en, tampermonkey/PPT_AutoComplete.js, test/spec/PptTestData.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/GroupMemberGrsControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/OrganisationDetailsTypeControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/RemoveMemberControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/group/GroupDetailSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/group/OrganisationDetailsTypeViewSpec.scala
=> PPTP-1407 Check if already added to this ppt group

app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/Registration.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/RegistrationSpec.scala
Add completed "other organisations in group" to count of completed sections
=> BAU - number of completed task sections for groups

app/uk/gov/hmrc/plasticpackagingtax/registration/config/AppConfig.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/unauthorised.scala.html, conf/app.routes, conf/messages.en, test/uk/gov/hmrc/plasticpackagingtax/registration/views/UnauthorisedViewSpec.scala
=> PPTP-1395 : Unauthorised Page Content Update

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewRegistrationController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/contact/ContactDetailsConfirmAddressController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/OrganisationDetailsTypeHelper.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/organisation/GrsController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/forms/organisation/OrganisationType.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/OrganisationDetails.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/group/organisation_type.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/organisation/organisation_type.scala.html, conf/messages.en, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/OrganisationDetailsTypeControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/organisation/OrganisationDetailsTypeControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/group/OrganisationDetailsTypeViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/organisation/OrganisationDetailsTypeViewSpec.scala
Handle overseas company with UK branch same as Uk Company (for GRS journey)
Requires BE change - https://github.com/hmrc/plastic-packaging-tax-registration/pull/97
=> PPTP-1288 - Integrate with Non UK company with UK Establishment

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/enrolment/CheckAnswersController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/enrolment/NotableErrorController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/enrolment/UserEnrolmentResponse.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/enrolment/reference_number_already_used_failure_page.scala.html, conf/app.routes, conf/messages.en, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/enrolment/CheckAnswersControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/enrolment/NotableErrorControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/enrolment/ReferenceNumberAlreadyUsedFailurePageSpec.scala
=> PPTP-1381 Enrolment belongs to another organisation' error page

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/GroupMemberGrsController.scala, conf/application.conf, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/GroupMemberGrsControllerSpec.scala
Allow overseas company with uk branch to be used as nominated and/or group member
=> PPTP-1491 - Groups - Enable Non UK Co with UK Establishment to register

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/NotableErrorController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/organisation/GrsController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/group/nominated_organisation_already_registered_page.scala.html, conf/app.routes, conf/messages.en, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/NotableErrorControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/organisation/GrsControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/group/NominatedOrganisationAlreadyRegisteredViewSpec.scala
=> PPTP-1490 Nominated Organisation Already Registered Page

tampermonkey/PPT_AutoComplete.js
- journey drop-down (Single, Group)
- orgType drop-down (UKBusiness, OverseasUkBranch)
- random GRS company name (allows multiple group members)
=> BAU - tampermonkey updates

project/AppDependencies.scala, project/plugins.sbt
=> BAU - dependency update

app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/Registration.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/components/Styles.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/contact/email_address_passcode_page.scala.html, conf/messages.en, test/uk/gov/hmrc/plasticpackagingtax/registration/views/contact/ContactDetailsEmailAddressPasscodeViewSpec.scala
=> Build new Email verification help page

app/uk/gov/hmrc/plasticpackagingtax/registration/views/partials/amendment/primaryContactDetails.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/utils/ViewUtils.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/contact/ContactDetailsEmailAddressViewSpec.scala
=> PPTP-1555 Put registration amendment links behind feature flag

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/amendment/AmendContactDetailsController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/amendment/AmendEmailAddressController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/amendment/AmendRegistrationController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/amendment/AmendmentController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/contact/ContactDetailsEmailAddressController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/contact/ContactDetailsEmailAddressPasscodeConfirmationController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/contact/ContactDetailsEmailAddressPasscodeController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/emailverification/EmailVerification.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/PrimaryContactDetails.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/request/AmendmentJourneyAction.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/services/EmailVerificationService.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/contact/email_address_passcode_confirmation_page.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/contact/email_address_passcode_page.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/partials/amendment/primaryContactDetails.scala.html, conf/app.routes, test/base/unit/MockAmendmentJourneyAction.scala, test/base/unit/MockRegistrationAmendmentRepository.scala, test/base/unit/MockSubscriptionConnector.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/amendment/AmendContactDetailsControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/amendment/AmendEmailAddressControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/amendment/AmendRegistrationControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/contact/ContactDetailsEmailAddressPasscodeConfirmationControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/contact/ContactDetailsEmailAddressPasscodeControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/models/request/AmendmentJourneyActionSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/repositories/UserDataRepositorySpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/services/EmailVerificationServiceSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/contact/ContactDetailsEmailAddressPasscodeConfirmationViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/contact/ContactDetailsEmailAddressPasscodeViewSpec.scala
There is a WAVE warning on the page used to capture the email verification code but this is present during the normal flow and thus is deemed acceptable here (the same page is reused).
=> PPTP-1552 : Verify Email During Reg Amendment

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/amendment/AmendmentController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/ConfirmGroupMemberBusinessAddressController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/GroupMemberGrsController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/OrganisationDetailsTypeController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/OrganisationDetailsTypeHelper.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/organisation/ConfirmBusinessAddressController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/organisation/GrsController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/organisation/OrganisationDetailsTypeController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/genericregistration/PartnershipBusinessDetails.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/genericregistration/PartnershipDetails.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/GroupDetail.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/OrganisationDetails.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/organisation/confirm_business_address.scala.html, conf/app.routes, conf/messages.en, test/base/unit/MockSubscriptionConnector.scala, test/spec/PptTestData.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/contact/ContactDetailsEmailAddressPasscodeConfirmationControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/ConfirmGroupMemberBusinessAddressControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/GroupMemberGrsControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/OrganisationDetailsTypeControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/organisation/ConfirmBusinessAddressControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/organisation/GrsControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/organisation/OrganisationDetailsTypeControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/contact/ContactDetailsEmailAddressPasscodeViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/organisation/ConfirmBusinessAddressViewSpec.scala
- Added confirm company address page
- Added the same for group member
- Changed the partnership selection to navigate to Grs
- Populating partnership details on grs call back
=> Create 'display registered address' page

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/OrganisationDetailsTypeController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/OrganisationDetailsTypeHelper.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/genericregistration/IncorpEntityGrsCreateRequest.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/genericregistration/PartnershipGrsCreateRequest.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/models/genericregistration/IncorpEntityGrsCreateRequestSpec.scala
=> PPTP-1492 Toggle off Business Verification for Group Members

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/ContactDetailsEmailAddressController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/ContactDetailsNameController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/ContactDetailsTelephoneNumberController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/GroupMemberGrsController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/forms/group/MemberName.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/GroupDetail.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/Registration.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/group/GroupMember.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/group/GroupMemberContactDetails.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/group/member_email_address_page.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/group/member_name_page.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/group/member_phone_number_page.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/partials/review/organisationDetails.scala.html, conf/app.routes, conf/messages.en, tampermonkey/PPT_AutoComplete.js, test/spec/PptTestData.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/ContactDetailsEmailAddressControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/ContactDetailsNameControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/ContactDetailsTelephoneNumberControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/GroupMemberGrsControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/organisation/CheckAnswersControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/group/GroupMemberContactDetailsSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/group/ContactDetailsEmailAddressViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/group/ContactDetailsNameViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/group/ContactDetailsPhoneNumberViewSpec.scala
=> PPTP-1387 Capture Contact details for Members

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/organisation/PartnershipNameController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/organisation/PartnershipTypeController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/forms/organisation/PartnershipName.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/organisation/partnership_name.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/partials/review/organisationDetails.scala.html, conf/app.routes, conf/messages.en, tampermonkey/PPT_AutoComplete.js, test/base/unit/MockConnectors.scala, test/spec/PptTestData.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewTaskListControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/contact/ContactDetailsConfirmAddressControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/organisation/GrsControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/organisation/PartnershipNameControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/organisation/PartnershipTypeControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/ReviewRegistrationViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/organisation/CheckAnswersPageViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/organisation/PartnershipNameViewSpec.scala
=> Pptp 1531 capture partnership name

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/ContactDetailsCheckAnswersController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/ContactDetailsTelephoneNumberController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/group/GroupMember.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/group/member_contact_check_answers_page.scala.html, conf/app.routes, conf/messages.en, test/spec/PptTestData.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/ContactDetailsCheckAnswersControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/ContactDetailsTelephoneNumberControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/group/ContactDetailsCheckAnswersViewSpec.scala
=> PPTP-1548 : Group Member Contact Details CYA

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/ConfirmContactAddressController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/ContactDetailsConfirmAddressController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/ContactDetailsTelephoneNumberController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/group/GroupMember.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/group/member_contact_check_answers_page.scala.html, conf/app.routes, conf/messages.en, test/base/unit/MockConnectors.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/ConfirmContactAddressControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/ContactDetailsTelephoneNumberControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/organisation/PartnershipNameControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/group/GroupMemberContactDetailsSpec.scala
=> PPTP-1566 Confirm / Capture Group member Contact Address (UK only)

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/ContactDetailsCheckAnswersController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/partials/review/groupMemberDetail.scala.html, conf/messages.en, test/uk/gov/hmrc/plasticpackagingtax/registration/views/ReviewRegistrationViewSpec.scala
=> PPTP-1585 Display Group Member Details

conf/app.routes, tampermonkey/PPT_AutoComplete.js
They need to be different from those used by partners.
=> PPTP-1602 : Update group member URLs

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerContactNameController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerEmailAddressController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerGrsController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerPhoneNumberController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/partner/partner_check_answers_page.scala.html, build.sbt, conf/app.routes, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerContactNameControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerEmailAddressControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerGrsControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerPhoneNumberControllerSpec.scala
Contact name, email and phone number cab be amended for existing partners.
=> Pptp 1550 Amend contact details

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/NominatedPartnerTypeController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerContactNameController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerGrsController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerListController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerTypeController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/genericregistration/Partner.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/genericregistration/PartnershipDetails.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/OrganisationDetails.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/Registration.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/organisation/partner_type.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/partner/partner_check_answers_page.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/task_list_partnership.scala.html, build.sbt, conf/app.routes, conf/messages.en, tampermonkey/PPT_AutoComplete.js, test/base/unit/MockConnectors.scala, test/spec/PptTestData.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/NominatedPartnerTypeControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerCheckAnswersControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerGrsControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerListControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerTypeControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/OrganisationDetailsSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/RegistrationPartnershipViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/organisation/PartnershipPartnerTypeViewSpec.scala
=> PPTP-1189 Select other partners entity type

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewRegistrationController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/TaskListController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/genericregistration/Partner.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/Registration.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/task_list_partnership.scala.html, build.sbt, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewTaskListControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/TaskListControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/RegistrationSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/RegistrationPartnershipViewSpec.scala
=> PPTP-1641 : Fixed Up Partnership Task-list

app/uk/gov/hmrc/plasticpackagingtax/registration/views/partials/review/organisationDetails.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/partials/review/partnerDetail.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/partials/review/partnerListDetails.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/review_registration_page.scala.html, conf/messages.en, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/TaskListControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/ReviewRegistrationViewSpec.scala
=> PPTP-1507 Partnership version of 'Review and send your registration'

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/RemovePartnerController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/forms/partner/RemovePartner.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/partner/partner_list_page.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/partner/remove_partner_page.scala.html, conf/app.routes, conf/messages.en, test/spec/PptTestData.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/RemovePartnerControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/partner/RemovePartnerViewSpec.scala
=> PPTP-1511 Remove partner

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/OrganisationDetailsTypeController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/OrganisationDetailsTypeHelper.scala
=> PPTP-1658 Group - LLP Registration Failure

build.sbt
=> Auto run scala fmt

app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/Registration.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/amendment/amend_registration_page.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/partials/amendment/organisationDetails.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/partials/amendment/primaryContactDetails.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/partials/review/liabilityDetails.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/utils/ViewUtils.scala, conf/messages.en, test/base/MockAuthAction.scala, test/spec/PptTestData.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/audit/AuditorSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/connectors/RegistrationConnectorSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/amendment/AmendRegistrationViewSpec.scala
Added Registration.dateOfRegistration to both FE and BE as required to be displayed on this page.
BE: https://github.com/hmrc/plastic-packaging-tax-registration/pull/132
=> PPTP-1673 : Refactor Main Amend Registration Page

app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/Registration.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/partials/amendment/organisationDetails.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/utils/ViewUtils.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/amendment/AmendRegistrationViewSpec.scala
BE: https://github.com/hmrc/plastic-packaging-tax-registration/pull/133
=> PPTP-1678 : Ensure Registration Changes Backwards Compatible

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/amendment/group/ConfirmRemoveMemberController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/RemoveMemberAction.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/RemoveMemberController.scala
Post merge duplication.
- updateRegistration can handle the onwards redirect
- deduplicate registration update function.
=> Pptp 1421 Duplicate update action

app/uk/gov/hmrc/plasticpackagingtax/registration/audit/CreateRegistrationEvent.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/audit/AuditorSpec.scala
Updated registration audit event with group details, registration type and date
=> PPTP-1677: added group and other minor elements to CIP audit event

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/amendment/group/ContactDetailsCheckAnswersController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/ContactDetailsCheckAnswersController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/OrganisationDetailsTypeControllerBase.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/OrganisationDetailsTypeHelper.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/organisation/OrganisationDetailsTypeController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/services/GRSRedirections.scala, test/spec/PptTestData.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/amendment/AmendContactDetailsControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/amendment/AmendEmailAddressControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/amendment/AmendOrganisationDetailsControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/amendment/AmendRegistrationControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/amendment/group/ConfirmRemoveMemberControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/amendment/group/ContactDetailsCheckAnswersControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/amendment/group/ManageGroupMembersControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/OrganisationDetailsTypeControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/organisation/OrganisationDetailsTypeControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/amendment/group/ManageGroupMembersPageSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/models/ListGroupMembersViewModelSpec.scala
=> PPTP-1676 Adding an LLP group member fails

app/uk/gov/hmrc/plasticpackagingtax/registration/views/task_list_partnership.scala.html, test/uk/gov/hmrc/plasticpackagingtax/registration/views/RegistrationPartnershipViewSpec.scala
Link swapped for view page only when nominated partner has been set other wise original functionality remains
=> PPTP-1644 | Nominated partner - task list link

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/amendment/partner/AmendPartnerContactDetailsController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/partials/amendment/primaryContactDetails.scala.html, build.sbt, conf/app.routes, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/amendment/partner/AmendPartnerContactDetailsControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/amendment/AmendRegistrationViewSpec.scala
=> PPTP-1686 : Nominated Partner Post Reg Amendment

conf/messages.en
"What's" -> "What is" on partnerships name page
=> Fix contraction in heading and page title on partnership name page

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/amendment/partner/AmendPartnerContactDetailsController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/partials/amendment/primaryContactDetails.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/partials/review/partnerDetail.scala.html, conf/app.routes, conf/messages.en, test/spec/PptTestData.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/amendment/partner/AmendPartnerContactDetailsControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/ReviewRegistrationViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/amendment/AmendRegistrationViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/partner/PartnerCheckAnswersViewSpec.scala
=> PPTP-1698 - Amend job title for nominated partner post reg

app/uk/gov/hmrc/plasticpackagingtax/registration/views/liability/liability_weight_expected_page.scala.html, conf/messages.en, test/uk/gov/hmrc/plasticpackagingtax/registration/views/liability/LiabilityExpectedWeightViewSpec.scala
=> PPTP-1184 | content changes for liability weight questions

app/uk/gov/hmrc/plasticpackagingtax/registration/views/liability/liability_weight_expected_page.scala.html, conf/messages.en, test/uk/gov/hmrc/plasticpackagingtax/registration/views/liability/LiabilityExpectedWeightViewSpec.scala
Info should be in the hint field for correct styling.
=> PPTP-1184 | correct styling

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerTypeControllerBase.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/services/GRSRedirections.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerTypeControllerSpec.scala
=> PPTP-1693 - Disable business verification for partners

conf/app.routes, conf/messages.en
Changed content on following pages:
-/business-details-not-matched
-/sole-trader-details-not-matched
=> PPTP-1691 Changed content

app/uk/gov/hmrc/plasticpackagingtax/registration/config/Features.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/liability/CheckLiabilityDetailsAnswersController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/liability/LiabilityController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/liability/LiabilityStartDateController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/liability/LiabilityWeightExpectedController.scala, conf/application.conf, tampermonkey/PPT_Auth_AutoComplete.js, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/liability/CheckLiabilityDetailsAnswersControllerTest.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/liability/LiabilityStartDateControllerTest.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/liability/LiabilityWeightExpectedControllerTest.scala
And the group related test users.
=> PPTP 1669 - Remove group registration feature flag

app/uk/gov/hmrc/plasticpackagingtax/registration/views/group/member_name_page.scala.html, conf/messages.en, test/uk/gov/hmrc/plasticpackagingtax/registration/views/group/ContactDetailsNameViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/partner/PartnerMemberNamePageViewSpec.scala
-Guidance content update
-Validation error messages updated in like with SSOT
=> PPTP-1696 Content change - Group member contact name

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/liability/ExpectToExceedThresholdWeightController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/forms/CommonFormValidators.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/forms/liability/ExpectToExceedThresholdWeight.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/forms/liability/LiabilityExpectToExceedThresholdWeight.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/Cacheable.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/liability/expect_to_exceed_threshold_weight_page.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/liability/liability_expect_to_exceed_threshold_weight_page.scala.html, conf/app.routes, conf/messages.en, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/liability/ExpectToExceedThresholdWeightControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/forms/liability/ExpectToExceedThresholdWeightSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/forms/liability/LiabilityExpectToExceedThresholdWeightSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/liability/ExpectToExceedThresholdWeightViewSpec.scala
I have renamed some of the _old_ stuff to be prefixed with Liability, all _new_ stuff is with out the prefix.. Github highlighting isnt picking this up perfectly, however there is no changes to the _old_ stuff just name space
=> PPTP-1713 | new forward look page

app/uk/gov/hmrc/plasticpackagingtax/registration/config/AppConfig.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/config/Module.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/liability/ExpectToExceedThresholdWeightDateController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/forms/liability/ExpectToExceedThresholdWeightDate.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/liability/expect_to_exceed_threshold_weight_date_page.scala.html, conf/app.routes, conf/application.conf, conf/messages.en, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/liability/ExpectToExceedThresholdWeightDateControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/forms/liability/ExpectToExceedThresholdWeightDateSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/liability/ExpectToExceedThresholdWeightDateViewSpec.scala
App Config Base: https://github.com/hmrc/app-config-base/pull/6821
=> PPTP-1737 : Liability Forward Look Date

tampermonkey/PPT_Auth_AutoComplete.js, tampermonkey/PPT_AutoComplete.js
- Adding Tampermonkey support for new nominated partner email address verification pages
- Updating version of auth script to be picked up in TM autoupdate
https://jira.tools.tax.service.gov.uk/browse/PPTP-1636
=> PPTP-1636 - TamperMonkey script updates

app/uk/gov/hmrc/plasticpackagingtax/registration/views/contact/confirm_address.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/review_registration_page.scala.html, conf/app.routes, conf/messages.en, test/uk/gov/hmrc/plasticpackagingtax/registration/forms/CommonFormValidatorsSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/contact/ContactDetailsConfirmAddressViewSpec.scala
=> tweaks as per content and design

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/liability/ExceededThresholdWeightDateController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/liability/ExpectToExceedThresholdWeightDateController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/liability/TaxStartDateController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/services/TaxStartDateService.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/liability/expect_to_exceed_threshold_weight_date_page.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/liability/tax_start_date_page.scala.html, conf/app.routes, conf/messages.en, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/liability/ExceededThresholdWeightDateControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/liability/ExpectToExceedThresholdWeightDateControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/liability/TaxStartDateControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/forms/liability/ExpectToExceedThresholdWeightDateSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/services/TaxStartDateServiceSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/liability/ExceededThresholdWeightDateViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/liability/ExpectToExceedThresholdWeightDateViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/liability/TaxStartDateViewSpec.scala
added more tests and save and continues button
linked pages to the TaxStartDate page
removed unused import
saved start date to db
purifing liablityDetails when save and sontinues on both exceeded and expect to exceed threshold weight pages
renamed
=> added Tax start date page

app/uk/gov/hmrc/plasticpackagingtax/registration/views/partials/liabilityCheckAnswers.scala.html, test/uk/gov/hmrc/plasticpackagingtax/registration/views/liability/CheckLiabilityDetailsAnswersViewSpec.scala
=> PPTP-1795 Fixed unable to post launch weight question and answer in CYA page

app/uk/gov/hmrc/plasticpackagingtax/registration/views/utils/ViewUtils.scala, conf/app.routes, conf/messages.en, test/uk/gov/hmrc/plasticpackagingtax/registration/views/ConfirmationViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/ReviewRegistrationViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/liability/CheckLiabilityDetailsAnswersViewSpec.scala
=> More content tweaks, this time groups

conf/messages.en, test/uk/gov/hmrc/plasticpackagingtax/registration/views/partner/PartnerRegistrationAvailableSoonPageViewSpec.scala
=> fix/PPTP-1736 | Change link to guidance to a support email address

app/uk/gov/hmrc/plasticpackagingtax/registration/forms/liability/ExceededThresholdWeightDate.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/forms/liability/ExpectToExceedThresholdWeightDate.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/forms/mappings/Constraints.scala, conf/messages.en, test/uk/gov/hmrc/plasticpackagingtax/registration/forms/liability/ExceededThresholdWeightDateSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/forms/liability/ExpectToExceedThresholdWeightDateSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/liability/ExceededThresholdWeightDateViewSpec.scala
=> PPTP-1788 Capture date breached threshold - Error Messages only

conf/messages.en
=> PPTP-1788 Updated the error message

tampermonkey/PPT_AutoComplete.js
Adding scripts to support the amend registration journey for single and group subscriptions
=> adding tamper monkey scripts for amend journey

app/uk/gov/hmrc/plasticpackagingtax/registration/config/AppConfig.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/LanguageController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/components/listMembers.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/main_template.scala.html, build.sbt, conf/app.routes, conf/application.conf, conf/messages.cy, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/LanguageControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/address/AddressViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/address/UkAddressViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/group/OrganisationListSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/organisation/OrganisationTypeNotSupportedViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/partner/PartnerListViewSpec.scala
Added framework for language switching. And feature toggle so this can be disabled until welsh translations are complete
=> PPTP-1750 | language switcher, with feature toggle

test/uk/gov/hmrc/plasticpackagingtax/registration/views/contact/ContactDetailsPhoneNumberViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/group/ContactDetailsPhoneNumberViewSpec.scala
=> fix unit tests from bad merge

conf/messages.en
=> fix/PPTP-1814-patch | Add full stop

app/uk/gov/hmrc/plasticpackagingtax/registration/views/amendment/group/list_group_members_page.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/components/listMembers.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/models/ListGroupMembersViewModel.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/amendment/group/ListGroupMembersPageSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/components/ListMembersSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/models/ListGroupMembersViewModelSpec.scala
=> remove border line and update group member message

app/uk/gov/hmrc/plasticpackagingtax/registration/views/group/organisation_type.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/liability/registration_type_page.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/organisation/organisation_type.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/organisation/register_as_other_organisation.scala.html, conf/messages.en, test/uk/gov/hmrc/plasticpackagingtax/registration/views/group/OrganisationDetailsTypeViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/organisation/OrganisationDetailsTypeViewSpec.scala
=> PPTP-1810: removed hint text from group or not page & one entry in messages file for gform link

app/uk/gov/hmrc/plasticpackagingtax/registration/views/liability/registration_type_page.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/organisation/register_as_other_organisation.scala.html, conf/messages.en, test/uk/gov/hmrc/plasticpackagingtax/registration/views/liability/RegistrationTypeViewSpec.scala
=> PPTP-1810_hint_needed

conf/messages.en
Small content updates after registration demo and review
=> Small content update after registration demo and review

conf/messages.en
=> PPTP-1823 Page title accessibility fix

conf/messages.en, test/uk/gov/hmrc/plasticpackagingtax/registration/views/contact/ContactDetailsFullNameViewSpec.scala
=> fix/PPTP-1844-2 | Add missing error message around full stops

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/deregistration/DeregisterCheckYourAnswersController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/deregistration/DeregisterController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/deregistration/DeregisterReasonController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/deregistration/DeregistrationSubmittedController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/deregistration/deregister_check_your_answers_page.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/deregistration/deregister_page.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/deregistration/deregister_reason_page.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/deregistration/deregistration_submitted_page.scala.html, build.sbt, conf/app.routes
Routing plus bare bones controllers and pages.
=> PPTP-1880 : Deregistration Skeleton - Phase I

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/deregistration/DeregisterController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/forms/deregistration/DeregisterForm.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/repositories/DeregistrationDetailRepository.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/deregistration/deregister_page.scala.html, build.sbt, conf/messages.en, test/base/unit/MockDeregistrationDetailRepository.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/deregistration/DeregisterControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/repositories/DeregistrationDetailRepositorySpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/deregistration/DeregisterViewSpec.scala
At present there are 3 view tests which are failing but, I can't for the life in me, find what the problem is.
=> PPTP-1889 : Are you sure you want to deregister page

app/uk/gov/hmrc/plasticpackagingtax/registration/views/deregistration/deregistration_submitted_page.scala.html, build.sbt, conf/messages.en, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/deregistration/DeregistrationSubmittedControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/deregistration/DeregistrationSubmittedViewSpec.scala
=> PPTP-1790 : Deregistration Confirmation

app/uk/gov/hmrc/plasticpackagingtax/registration/config/AppConfig.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/unauthorised.scala.html, conf/app.routes, conf/application.conf, conf/messages.en, test/uk/gov/hmrc/plasticpackagingtax/registration/views/UnauthorisedViewSpec.scala
Unauthorised Page - Remove link to Private Beta by 31/03/22
https://github.com/hmrc/plastic-packaging-tax-acceptance/pull/119
=> feature/PPTP-1873 | Remove link to Private Beta by 31/03/22

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/deregistration/DeregisterReasonController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/forms/deregistration/DeregisterReasonForm.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/deregistration/DeregistrationDetails.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/deregistration/DeregistrationReason.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/deregistration/deregister_reason_page.scala.html, build.sbt, conf/messages.en, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/deregistration/DeregisterReasonControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/deregistration/DeregistrationSubmittedControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/deregistration/DeregisterReasonViewSpec.scala
=> PPTP-1890: deregistration reason

app/uk/gov/hmrc/plasticpackagingtax/registration/audit/Auditor.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/audit/CreateRegistrationEvent.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/audit/StartRegistrationEvent.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewRegistrationController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/StartRegistrationController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/request/JourneyAction.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/audit/AuditorSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewTaskListControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/models/request/JourneyActionSpec.scala
=> PPTP-1849 Add new audit event to registration service and enhance two other existing ones

conf/application.conf
=> PPTP-1911: disable allowlist for go-live by removing all email addresses & setting ukCompanyPrivateBeta to false

app/uk/gov/hmrc/plasticpackagingtax/registration/views/deregistration/deregister_check_your_answers_page.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/deregistration/deregister_reason_page.scala.html, conf/messages.en, test/uk/gov/hmrc/plasticpackagingtax/registration/views/deregistration/DeregisterCheckYourAnswersViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/deregistration/DeregisterReasonViewSpec.scala
=> PPTP-1787 Name changes

conf/messages.cy, conf/messages.en
=> PPTP-1237 - Adding Welsh translations, and removing redundant messages

build.sbt
=> Lower scoverage

app/uk/gov/hmrc/plasticpackagingtax/registration/views/duplicate_subscription_page.scala.html, conf/messages.cy, conf/messages.en, test/uk/gov/hmrc/plasticpackagingtax/registration/views/DuplicateSubscriptionViewSpec.scala
=> corrected the ppt account link format

app/uk/gov/hmrc/plasticpackagingtax/registration/views/partner/partner_list_page.scala.html, test/uk/gov/hmrc/plasticpackagingtax/registration/views/partner/PartnerListViewSpec.scala
=> PPTP-1807: hide remove partnership button if there are 2 or les partners

app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/OrganisationDetails.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/OrganisationDetailsSpec.scala
=> PPTP-1708: Fixed Scottish limited partnership

app/uk/gov/hmrc/plasticpackagingtax/registration/views/liability/exceeded_threshold_weight_page.scala.html, conf/messages.cy, conf/messages.en
=> Add hint text to please policy

app/uk/gov/hmrc/plasticpackagingtax/registration/views/duplicate_subscription_page.scala.html, conf/messages.cy, conf/messages.en, test/uk/gov/hmrc/plasticpackagingtax/registration/views/DuplicateSubscriptionViewSpec.scala
=> PPTP-2006: removed link

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/UnauthorisedController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/actions/AuthAction.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/unauthorised_not_admin.scala.html, conf/app.routes, conf/messages.cy, conf/messages.en, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/UnauthorisedControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/actions/AuthActionSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/repositories/DeregistrationDetailRepositorySpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/repositories/UserDataRepositorySpec.scala
=> PPTP-1998: Credential role check and dropout page

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/amendment/partner/AmendPartnerContactDetailsController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerContactNameControllerBase.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/partner/partner_member_name_page.scala.html, conf/messages.cy, conf/messages.en, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/amendment/partner/AmendPartnerContactDetailsControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerContactNameControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/partner/PartnerMemberNamePageViewSpec.scala
=> Partner contact name fixes Nom and Other

app/uk/gov/hmrc/plasticpackagingtax/registration/views/amendment/partner/list_partners_page.scala.html, test/uk/gov/hmrc/plasticpackagingtax/registration/views/amendment/partner/ListPartnersPageSpec.scala
=> hiding remove button for post registration partnership

app/uk/gov/hmrc/plasticpackagingtax/registration/connectors/grs/GrsConnector.scala
=> switch off BV for all, just in case

app/uk/gov/hmrc/plasticpackagingtax/registration/views/organisation/partner_type.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/organisation/partnership_type.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/partner/partner_member_name_page.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/partner/partner_name_page.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/partner/remove_partner_page.scala.html, conf/messages.cy, conf/messages.en, test/uk/gov/hmrc/plasticpackagingtax/registration/views/organisation/PartnershipPartnerTypeViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/organisation/PartnershipTypeViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/partner/PartnerMemberNamePageViewSpec.scala
=> Second round of partnership content fixes

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/partner/PartnerGrsControllerBase.scala
=> Now with Grs Failed instead of Not supported

app/uk/gov/hmrc/plasticpackagingtax/registration/services/CountryService.scala
=> Added some logging to identify synonyms in country names

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/organisation/GrsController.scala, conf/messages.cy, conf/messages.en, test/spec/PptTestData.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/organisation/GrsControllerSpec.scala
=> PPTP-2092 | make other grs callback like partners grs callback

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/organisation/GrsController.scala
=> Align to partnerships

conf/messages.cy
Added Welsh for is address in UK page
=> Added Welsh for is address in UK page

tampermonkey/PPT_AutoComplete.js
- Starts section 2 instead of clicking the Welsh language link
- Selects `Review registration` for at end of Groups journey
- Selects `Partnership` type on partner-type page
=> Fixing task-list issues

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/liability/ExceededThresholdWeightController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/liability/ExpectToExceedThresholdWeightController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/services/TaxStartDateService.scala
=> Skip date pages, force start date

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/GroupMemberGrsControllerBase.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/genericregistration/IncorporationDetails.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/OrganisationDetails.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/amendment/partner/amend_add_partner_contact_check_answers_page.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/partials/review/organisationDetails.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/partials/review/partnerDetail.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/partner/partner_check_answers_page.scala.html, test/builders/RegistrationBuilder.scala, test/spec/PptTestData.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/ReviewTaskListControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/GroupMemberGrsControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/OrganisationDetailsSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/services/RegistrationGroupFilterServiceSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/ReviewRegistrationViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/amendment/partner/AmendAddPartnerContactCheckAnswersViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/organisation/CheckAnswersPageViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/partner/PartnerCheckAnswersViewSpec.scala
Enable gforms users to log into the service and see their subscription details / submit amendments.
=> Added support for gform registered entities

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/liability/ExpectToExceedThresholdWeightController.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/liability/ExpectToExceedThresholdWeightControllerSpec.scala
=> fixed controller tests

tampermonkey/PPT_AutoComplete.js
=> PPTP-2265 - Tamper monkey updates

conf/messages.cy
=> Check your answer welsh

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/amendment/group/AddGroupMemberConfirmBusinessAddressController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/amendment/group/AddGroupMemberGrsController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/group/GroupMemberGrsControllerBase.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/organisation/ConfirmBusinessAddressController.scala, conf/app.routes, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/amendment/group/AddGroupMemberConfirmBusinessAddressControllerSpec.scala
Fixes bug where post-subscription it wasn't possible to add a group member.
=> PPTP-2425: Bug fix for add member to group amendment

app/uk/gov/hmrc/plasticpackagingtax/registration/views/components/conditionalYesNoRadio.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/liability/exceeded_threshold_weight_page.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/liability/expect_to_exceed_threshold_weight_page.scala.html, conf/messages.cy, conf/messages.en, test/uk/gov/hmrc/plasticpackagingtax/registration/views/liability/ExceededThresholdWeightViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/liability/ExpectToExceedThresholdWeightViewSpec.scala
Content concerned now wrapped as requested and tests updated
=> PPTP-2392: Acc Reg - Ungrouped page content

conf/messages.cy, conf/messages.en
=> edited validation message

app/uk/gov/hmrc/plasticpackagingtax/registration/views/liability/liability_weight_page.scala.html, conf/messages.cy, conf/messages.en, test/uk/gov/hmrc/plasticpackagingtax/registration/views/liability/LiabilityWeightViewSpec.scala
=> added hint

test/uk/gov/hmrc/plasticpackagingtax/registration/views/ConfirmationViewSpec.scala
Quick fix for test broken by change of date
=> Fix date-bomb in tests

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/enrolment/CheckAnswersController.scala
Previous saw "problem with service" page
=> Users with GroupEnrolmentFailed aka incorrect known facts will now see enrolmentVerificationFailurePage

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/NotableErrorController.scala
we dont need alerts for this anymore more
=> /registration-failed to return 200 not 500

project/AppDependencies.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/address/AddressViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/address/UkAddressViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/amendment/AmendRegistrationViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/contact/ContactDetailsPhoneNumberViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/group/ContactDetailsPhoneNumberViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/group/OrganisationListSpec.scala
=> [PPTP-2608, PPTP-2610]: upgraded banner to fix accessibility issues

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/UpdateCompaniesHouseController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/contact/ContactDetailsConfirmAddressController.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/forms/contact/Address.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/OrganisationDetails.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/models/registration/Registration.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/UpdateCompaniesHouseView.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/components/link.scala.html, conf/app.routes, conf/messages.cy, conf/messages.en, test/builders/RegistrationBuilder.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/UpdateCompaniesHouseControllerSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/contact/ContactDetailsConfirmAddressControllerSpec.scala
=> PPTP-2505 | Advice page for users with no country code

conf/messages.cy, conf/messages.en
Updating the content displayed if the user selects no radio option.
=> PPTP-2624 - Updating empty error content

app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/actions/NotEnrolledAuthAction.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/controllers/actions/NotEnrolledAuthActionSpec.scala
=> PPTP-2648: redirect to the right url

app/uk/gov/hmrc/plasticpackagingtax/registration/services/CountryService.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/utils/ViewUtils.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/services/CountryServiceSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/amendment/AmendRegistrationViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/amendment/group/AmendMemberContactDetailsCheckAnswersViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/amendment/group/MemberContactDetailsCheckAnswersViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/amendment/partner/AmendAddPartnerContactCheckAnswersViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/amendment/partner/AmendPartnerContactCheckAnswersViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/group/ContactDetailsCheckAnswersViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/partner/PartnerCheckAnswersViewSpec.scala
=> PPTP-2647 | Stop country service exceptions for unknowns ISO codes

a11y/registration/deregistration/DeregisterCheckYourAnswersViewA11ySpec.scala, a11y/registration/deregistration/DeregisterReasonViewA11ySpec.scala, a11y/registration/deregistration/DeregisterViewA11ySpec.scala, a11y/registration/deregistration/DeregistrationSubmittedViewA11ySpec.scala, app/uk/gov/hmrc/plasticpackagingtax/registration/views/deregistration/deregister_check_your_answers_page.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/deregistration/deregister_page.scala.html, app/uk/gov/hmrc/plasticpackagingtax/registration/views/deregistration/deregister_reason_page.scala.html, test/uk/gov/hmrc/plasticpackagingtax/registration/views/deregistration/DeregisterCheckYourAnswersViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/deregistration/DeregisterReasonViewSpec.scala, test/uk/gov/hmrc/plasticpackagingtax/registration/views/deregistration/DeregisterViewSpec.scala
=> Adding deregistration view a11y specs

app/uk/gov/hmrc/plasticpackagingtax/registration/views/enrolment/check_answers_page.scala.html, test/uk/gov/hmrc/plasticpackagingtax/registration/views/enrolment/CheckAnswersViewSpec.scala
=> Use viewUtil date fmt

app/controllers/partner/PartnerTypeControllerBase.scala
Change required after GRS deprecated previously used endpoint - https://github.com/hmrc/sole-trader-identification-frontend/commit/f49e4c6e0e248afd80227ce3e994769e9fe89729
=> Update sole trader journey url for partnerships

app/controllers/testOnly/SkipAuthStubController.scala, app/controllers/testOnly/SkipAuthView.scala.html, conf/testOnlyDoNotUseInAppConf.routes
=> Hack around page with auto filled Wizard params for UR on staging

project/AppDependencies.scala, project/plugins.sbt
=> Additional updates

a11y/registration/liability/ExceededThresholdWeightDateViewA11ySpec.scala, a11y/registration/liability/ExceededThresholdWeightViewA11ySpec.scala, tampermonkey/PPT_AutoComplete.js
- Updating TamperMonkey journey scripts
- Adding a11y specs for exceeded threshold pages
=> PPTP-2609 - Liability TamperMonkey and A11y specs

app/views/address/address_page.scala.html, project/AppDependencies.scala
Refer to https://confluence.tools.tax.service.gov.uk/pages/viewpage.action?pageId=869794230
=> DDCYLS-3414: address country select dropdown issue

app/config/AppConfig.scala, app/controllers/SignOutController.scala, app/controllers/enrolment/NotableErrorController.scala, app/views/enrolment/enrolment_failure_page.scala.html, app/views/registration_failed_page.scala.html, conf/application.conf, test/controllers/SignOutControllerSpec.scala
Update sign out to conform to OLFG requirements
=> Update sign out to conform to OLFG requirements

app/assets/stylesheets/application.scss, app/views/main_template.scala.html, conf/application.conf, project/AppDependencies.scala
=> DDCYLS-7217: GOV UK rebrand feature flag enabled and compilation error fixes
